@id=bab78761-c36a-4b8b-9803-63bc2a628282

PUT http://localhost:5096/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "VVegan SSunshiners",
    "Desc": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}
